"use client";
import { useState } from "react";

const modules = ["Visão geral","Alunos","Boletins","Financeiro","Pix","Comunicados","Calendário","Contratos","Equipe","Auditoria"];
const students = [{name:"Ana Souza",group:"5º Ano A",status:"Ativa"},{name:"Lucas Lima",group:"7º Ano B",status:"Ativo"},{name:"Marina Costa",group:"3º Ano A",status:"Ativa"}];
export default function Home(){
 const [view,setView]=useState<"showcase"|"login"|"app">("showcase"),[active,setActive]=useState("Visão geral"),[toast,setToast]=useState("");
 const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2400)};
 if(view==="showcase") return <main className="showcase"><nav><b>AgentO<span>Studio</span></b><a href="https://github.com/fabiobrito01">GitHub</a></nav><section className="hero"><div className="tag">PRODUTOS PRIVADOS · DEMONSTRAÇÕES PÚBLICAS</div><h1>Tecnologia prática<br/><em>para negócios reais.</em></h1><p>Conheça experiências demonstrativas dos produtos AgentOStudio sem acesso a código, dados ou infraestrutura privada.</p><button onClick={()=>setView("login")}>Explorar sistema escolar <span>→</span></button></section><section className="products"><article className="featured"><div><small>DEMONSTRAÇÃO DISPONÍVEL</small><h2>Sistema Escolar de Gestão</h2><p>Administração, financeiro, comunicação e acompanhamento escolar em uma experiência integrada.</p><ul><li>Gestão acadêmica</li><li>Financeiro e Pix</li><li>Comunicação escolar</li></ul><button onClick={()=>setView("login")}>Abrir demonstração</button></div><div className="mock"><div className="mockbar"/><div className="mockgrid"><i/><i/><i/></div><div className="mockline"/><div className="mockline short"/></div></article><div className="soon"><article><b>Gestão de Condomínios</b><p>Comunicação, ocorrências e reservas.</p><span>Em preparação</span></article><article><b>Automação para Negócios</b><p>Rotinas, clientes e produtividade.</p><span>Em preparação</span></article></div></section><footer>Demonstrações independentes · Nenhum dado real · © 2026 AgentOStudio</footer></main>;
 if(view==="login") return <main className="login"><button className="back" onClick={()=>setView("showcase")}>← Voltar à vitrine</button><form onSubmit={e=>{e.preventDefault();setView("app")}}><div className="schoolmark">A</div><h1>Sistema Escolar</h1><p>Ambiente demonstrativo com dados fictícios</p><label>E-mail<input value="demo@agentostudio.com.br" readOnly/></label><label>Senha<input type="password" value="demonstracao" readOnly/></label><button>Entrar na demonstração</button><small>Nenhuma informação enviada ou armazenada.</small></form></main>;
 return <main className="dashboard"><header><b>Sistema Escolar de Gestão</b><div><button onClick={()=>notify("Nenhuma notificação nova")}>●</button><button onClick={()=>setView("showcase")}>Sair</button></div></header><aside><div className="schoolbrand"><span>A</span><b>Escola Demonstração</b></div><div className="person"><i>AD</i><span><b>Administrador</b><small>Perfil demonstrativo</small></span></div><nav>{modules.map(m=><button key={m} className={active===m?"on":""} onClick={()=>setActive(m)}>{m}</button>)}</nav></aside><section className="content"><div className="crumb">Demonstração / {active}</div>{active==="Visão geral"?<><div className="welcome"><div><small>BEM-VINDO</small><h1>Escola Demonstração AgentOStudio</h1><p>Uma visão clara da rotina acadêmica, administrativa e financeira.</p></div><button onClick={()=>notify("Matrícula simulada iniciada")}>+ Nova matrícula</button></div><div className="metrics"><article><small>Alunos ativos</small><strong>284</strong><span>+12 neste mês</span></article><article><small>Recebimentos</small><strong>92%</strong><span>Julho de 2026</span></article><article><small>Comunicados</small><strong>8</strong><span>3 não lidos</span></article><article><small>Turmas</small><strong>14</strong><span>Manhã e tarde</span></article></div><div className="twocol"><article><h3>Atividades recentes</h3>{["Pagamento registrado","Matrícula atualizada","Comunicado publicado"].map((x,i)=><p key={x}><b>{x}</b><small>há {i+1} hora{ i?"s":""}</small></p>)}</article><article><h3>Próximos eventos</h3><p><b>18 JUL</b> Reunião de responsáveis</p><p><b>22 JUL</b> Avaliação pedagógica</p><p><b>29 JUL</b> Encerramento do bimestre</p></article></div></>:active==="Alunos"?<div className="panel"><div className="panelhead"><div><h1>Alunos</h1><p>Cadastros demonstrativos</p></div><button onClick={()=>notify("Novo cadastro simulado")}>+ Cadastrar aluno</button></div><input className="search" placeholder="Pesquisar aluno ou turma"/>{students.map(s=><div className="row" key={s.name}><i>{s.name[0]}</i><span><b>{s.name}</b><small>{s.group}</small></span><mark>{s.status}</mark><button onClick={()=>notify(`Ficha de ${s.name} aberta`)}>Ver ficha</button></div>)}</div>:<div className="panel module"><span>{active.slice(0,2).toUpperCase()}</span><h1>{active}</h1><p>Este módulo demonstra a organização visual do produto. Nenhuma ação altera dados reais.</p><button onClick={()=>notify(`${active}: ação demonstrativa concluída`)}>Executar ação de exemplo</button></div>}</section>{toast&&<div className="toast">✓ {toast}</div>}<div className="demoFlag">DEMONSTRAÇÃO · DADOS FICTÍCIOS</div></main>
}
